language: perl
perl:
  - '5.8'
  - '5.10'
  - '5.12'
  - '5.14'
  - '5.16'
  - '5.18'
  - '5.20'
  - '5.22'
  - '5.24'
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - 'cpanm -n Crypt::CBC'
  - 'cpanm -n Crypt::Rijndael'
  - 'cpanm -n Carp'
  - 'cpanm -n Moo'
  - 'cpanm -n Test::Most'
  - 'cpanm -n Try::Tiny'
  - 'cpanm -n YAML::XS'
  - 'cpanm -n JSON'
  - 'cpanm -n Devel::Cover::Report::Coveralls'
  - 'cpanm -n Test::NoWarnings'
script:
  perl Makefile.PL && make test && cover -test -report coveralls

